server:
  #服务端口
  port: 12003
  servlet:
    context-path: /api



spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    #服务名称
    name: TestHub
  servlet:
    multipart:
      max-file-size: 50MB #单个文件大小
      max-request-size: 500MB # 一个次请求中上传文件的总容量的限制
  profiles:
    #指明使用的数据库
    active: h2
#    active: pgsql
    #导入其他yml文件
    include: testhub,actuator,mybatisplus
logging:
  config: classpath:config/logback-spring.xml


